### ISSUE TITLE
I use angularjs make a directive build iCheck UI

### ISSUE THREAD

**Issue by einsitang** [drgullin/icheck#169] opened 2014-05-06 10:35 UTC
this is the code.

```
return function(scope, element, attr) {

            //初始化iCheck样式
            var bool =  attr.iCheck;

            element[0].checked = !!bool;

            console.log(element[0],bool);

            element.iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue'
            })
            .on('ifClicked', function(event) {
                event.target.click();
            });

            }
    });

```

but my DOM has attribute ng-checked='xxx===xxx',and the iCheck cant build checked.

how can I do ?

**Comment by drgullin** [comment] 2015-01-12 10:54
Duplicate of #62.

**Closed as completed by drgullin** 2015-01-12 10:54 UTC
Labels: incorrect
