### ISSUE TITLE
Cool plugin ! But is it possible to Integrate iCheck with knockout? I tried to do so and didn't get the expected results !

### ISSUE THREAD

**Issue by chamweer** [drgullin/icheck#120] opened 2014-01-23 01:39 UTC
## binding

ko.bindingHandlers.RadioButton = {
    init: function (element, valueAccessor) {
        //initialize plugin
        $(element).iCheck({
            radioClass: 'iradio_square-blue'
        });

```
    $(element).on('ifChecked', function () {
        //try to change the observable value
        var observable = valueAccessor();
        observable.checked = true;          

    });
},
update: function (element, valueAccessor) {
    var observable = valueAccessor();
    debugger;
    //initially fired but on change of value it does not fired
}
```

};

**Comment by drgullin** [comment] 2014-01-23 09:50
Duplicate of #4

**Closed as completed by drgullin** 2014-01-23 09:50 UTC
Labels: questions
