### ISSUE TITLE
Register as a bower package

### ISSUE THREAD

**Issue by shirazz** [drgullin/icheck#76] opened 2013-09-16 15:33 UTC
Hi,

It would be better if you could register iCheck as a bower package. Now its possible to find iCheck from bower component list but i think the bower.json file is missing which makes it difficult to point the main file.  adding a sample bower.json file which may help you, not sure :) ..

{
    "name": "jquery-iCheck",
    "description": "Highly customizable checkboxes and radio buttons for jQuery and Zepto.",
    "version": "0.9.1",
    "dependencies": {
        "jquery": ">=1.8.1"
    },
    "keywords": [
        "radio",
        "checkboxes",
        "jQuery"
    ],
    "authors": [
        {
            "name": "Damir",
            "url": "http://damirfoy.com/iCheck/",
            "email": "info@fronteed.com"
        }
    ],
    "licenses": [
        {
            "type": "MIT",
            "url": "http://www.opensource.org/licenses/mit-license.php"
        }
    ],
    "homepage": "http://fronteed.com",
    "main": "jquery.icheck.js"
}

**Comment by drgullin** [comment] 2013-10-01 08:06
Package will be registered once plugin is updated to v2.0.

**Comment by Merg1255** [comment] 2013-10-17 03:45
@fronteed hi! We're interested in using this plugin. Could you please let us know when you plan to release the next versions?

Actually, it's really important to have the plugin work nice with Bootstra v3, since it's commonly used by people. :)

**Comment by jvandyke** [comment] 2013-12-18 21:25
This is a duplicate of https://github.com/fronteed/iCheck/issues/34

**Comment by jvandyke** [comment] 2013-12-18 21:28
@fronteed What's the hold up with this? It's trivial to do, and when you update to 2.0, you can just bump up the version.

At the very least, tag your code so people can lock down versions. We've had so many breaking changes from this repo that we've been forced to fork it and tag the copy ourselves (https://github.com/ktgit/iCheck).

**Closed as completed** 2013-12-19 13:39 UTC
Labels: features
